# Generated by Django 6.1 on 2026-08-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_batch'),
        ('questions', '0002_question_function_signature_question_wrapper_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='unlocked_batches',
            field=models.ManyToManyField(blank=True, to='accounts.batch'),
        ),
    ]
