# Generated by Django 6.1 on 2026-08-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_batch'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceday',
            name='unlocked_batches',
            field=models.ManyToManyField(blank=True, to='accounts.batch'),
        ),
    ]
