# Generated by Django 6.1 on 2026-08-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_practiceday_unlocked_batches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceday',
            name='is_unlocked',
        ),
    ]
